ArgumentOutOfRangeException: upgrade to /** */ Doxygen, add (message,inner) ctor, (paramName,actualValue,message) ctor, getActualValueProperty(), ThrowIfZero/Negative/NegativeOrZero/GreaterThan/GreaterThanOrEqual/LessThan/LessThanOrEqual/Equal/NotEqual; 36 new tests